services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local